/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

const { Plugin, ItemView, WorkspaceLeaf, Notice, Setting, PluginSettingTab } = require('obsidian');

const TIMELINE_VIEW_TYPE = 'timeline-view';

// 默认设置
const DEFAULT_SETTINGS = {
  includeAllFolders: true,
  specificFolders: [],
  taskFilter: 'pending', // all, completed, pending
  timelineName: '时间轴'
};

class TimelineView extends ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }

  getViewType() {
    return TIMELINE_VIEW_TYPE;
  }

  getDisplayText() {
    return '';
  }

  getIcon() {
    return 'leaf';
  }

  async onOpen() {
    const container = this.containerEl.children[1];
    
    // 先清理事件监听器，再清空容器
    // 清理可能存在的旧事件监听器，避免重复
    const oldDateContainers = document.querySelectorAll('.timeline-date');
    console.log('清理前找到的timeline-date元素数量:', oldDateContainers.length);
    oldDateContainers.forEach((dateEl, index) => {
      console.log('检查第', index, '个dateContainer元素:', dateEl._uniqueId);
      if (dateEl._contextMenuHandler) {
        console.log('清理第', index, '个元素的事件监听器:', dateEl._uniqueId);
        dateEl.removeEventListener('contextmenu', dateEl._contextMenuHandler);
        delete dateEl._contextMenuHandler;
        console.log('已清理事件监听器');
      }
    });
    
    // 清理任务容器的事件监听器
    const oldTaskContainers = document.querySelectorAll('.timeline-task-container');
    console.log('清理前找到的timeline-task-container元素数量:', oldTaskContainers.length);
    oldTaskContainers.forEach((taskEl, index) => {
      console.log('检查第', index, '个taskContainer元素:', taskEl._uniqueId);
      if (taskEl._contextMenuHandler) {
        console.log('清理第', index, '个任务容器的事件监听器:', taskEl._uniqueId);
        taskEl.removeEventListener('contextmenu', taskEl._contextMenuHandler);
        delete taskEl._contextMenuHandler;
        console.log('已清理任务容器事件监听器');
      }
    });
    
    // 清空容器
    container.empty();
    
    // 创建时间轴容器
    const timelineWrapper = container.createEl('div', { cls: 'timeline-wrapper' });
    
    // 创建筛选控件容器
    const headerContainer = timelineWrapper.createEl('div', { cls: 'timeline-header' });
    
    // 创建筛选控件
    const filterContainer = headerContainer.createEl('div', { cls: 'timeline-filter' });
    
    const filters = [
      { value: 'all', label: '全部' },
      { value: 'completed', label: '已完成' },
      { value: 'pending', label: '未完成' }
    ];
    
    filters.forEach(filter => {
      const button = filterContainer.createEl('button', {
        text: filter.label,
        cls: this.plugin.settings.taskFilter === filter.value ? 'active' : ''
      });
      button.addEventListener('click', async () => {
        this.plugin.settings.taskFilter = filter.value;
        await this.plugin.saveSettings();
        await this.onOpen();
      });
    });
    
    const timeline = timelineWrapper.createEl('div', { cls: 'timeline' });
    
    // 获取待办事项
    const tasks = await this.getTasks();
    
    // 按创建时间排序
    tasks.sort((a, b) => new Date(a.created).getTime() - new Date(b.created).getTime());
    
    // 应用筛选
    const filteredTasks = tasks.filter(task => {
      if (this.plugin.settings.taskFilter === 'completed') {
        return task.completed;
      } else if (this.plugin.settings.taskFilter === 'pending') {
        return !task.completed;
      }
      return true;
    });
    
    // 创建任务项
    filteredTasks.forEach((task, index) => {
      const side = index % 2 === 0 ? 'left' : 'right';
      const timelineItem = timeline.createEl('div', { cls: `timeline-item ${side}` });
      const content = timelineItem.createEl('div', { cls: 'timeline-content' });
      
      // 格式化日期
      const date = new Date(task.created);
      const formattedDate = date.toISOString().split('T')[0];
      
      // 创建日期容器，包含日期和标记
      const dateContainer = content.createEl('div', { cls: 'timeline-date' });
      dateContainer.style.display = 'flex';
      dateContainer.style.alignItems = 'center';
      dateContainer.style.justifyContent = 'space-between';
      
      // 添加日期文本
      const dateText = dateContainer.createEl('span');
      dateText.textContent = formattedDate;
      
      // 添加标记容器
      const markersContainer = dateContainer.createEl('div');
      markersContainer.style.display = 'flex';
      markersContainer.style.gap = '4px';
      markersContainer.style.alignItems = 'center';
      
      // 为日期容器添加唯一标识
      dateContainer._uniqueId = 'date-' + Date.now() + '-' + Math.random().toString(36).substr(2, 9);
      
      // 为日期容器添加右键菜单事件 - 添加标记
      dateContainer._contextMenuHandler = function(e) {
        // 关闭所有现有的上下文菜单
        const existingMenus = document.querySelectorAll('.timeline-context-menu');
        existingMenus.forEach(menu => {
          if (menu.parentNode === document.body) {
            document.body.removeChild(menu);
          }
        });
        
        e.preventDefault();
        e.stopPropagation();
        
        // 创建上下文菜单
        const menu = document.createElement('div');
        menu.className = 'timeline-context-menu';
        console.log('创建日期菜单:', menu);
        menu.style.position = 'fixed';
        menu.style.left = `${e.clientX}px`;
        menu.style.top = `${e.clientY}px`;
        menu.style.zIndex = '9999';
        menu.style.backgroundColor = '#333';
        menu.style.color = 'white';
        menu.style.border = '1px solid #666';
        menu.style.borderRadius = '4px';
        menu.style.boxShadow = '0 2px 8px rgba(0, 0, 0, 0.3)';
        menu.style.minWidth = '150px';
        menu.style.padding = '5px 0';
        menu.style.fontFamily = 'system-ui, -apple-system, BlinkMacSystemFont, sans-serif';
        menu.style.fontSize = '14px';
        
        // 生成菜单选项
        const menuOptions = [];
        
        // 根据任务的标记状态动态生成菜单选项
        if (!task.important) {
          menuOptions.push({ action: 'important', text: '标记重要' });
        }
        
        if (!task.urgent) {
          menuOptions.push({ action: 'urgent', text: '标记紧急' });
        }
        
        if (task.important) {
          menuOptions.push({ action: 'remove-important', text: '取消重要' });
        }
        
        if (task.urgent) {
          menuOptions.push({ action: 'remove-urgent', text: '取消紧急' });
        }
        
        menuOptions.forEach(option => {
          const item = document.createElement('div');
          item.className = 'menu-item';
          item.dataset.action = option.action;
          item.textContent = option.text;
          item.style.padding = '8px 15px';
          item.style.cursor = 'pointer';
          item.style.whiteSpace = 'nowrap';
          item.style.userSelect = 'none';
          
          // 添加悬停效果
          item.addEventListener('mouseenter', function() {
            this.style.backgroundColor = '#555';
          });
          
          item.addEventListener('mouseleave', function() {
            this.style.backgroundColor = 'transparent';
          });
          
          // 添加点击事件
          item.addEventListener('click', function(e) {
            e.stopPropagation();
            handleMenuAction(option.action);
          });
          
          menu.appendChild(item);
        });
        
        // 添加到文档
        document.body.appendChild(menu);
        
        // 处理菜单操作
        function handleMenuAction(action) {
          switch (action) {
            case 'important':
              // 标记为重要
              task.important = true;
              updateTaskMarks(task);
              break;
            case 'urgent':
              // 标记为紧急
              task.urgent = true;
              updateTaskMarks(task);
              break;
            case 'remove-important':
              // 取消重要标记
              task.important = false;
              updateTaskMarks(task);
              break;
            case 'remove-urgent':
              // 取消紧急标记
              task.urgent = false;
              updateTaskMarks(task);
              break;
            default:
              console.log('未知操作:', action);
          }
          
          // 移除菜单
          try {
            if (menu && menu.parentNode === document.body) {
              document.body.removeChild(menu);
            }
          } catch (err) {
            console.error('移除菜单时出错:', err);
          }
        }
        
        // 点击菜单外部关闭菜单
        function closeMenuOnOutsideClick(e) {
          try {
            if (menu && !menu.contains(e.target)) {
              if (menu.parentNode === document.body) {
                document.body.removeChild(menu);
                document.removeEventListener('click', closeMenuOnOutsideClick);
              }
            }
          } catch (err) {
            console.error('移除菜单时出错:', err);
            document.removeEventListener('click', closeMenuOnOutsideClick);
          }
        }
        
        // 添加外部点击事件监听器
        setTimeout(() => {
          document.addEventListener('click', closeMenuOnOutsideClick);
        }, 10);
        
        // 更新任务标记
        function updateTaskMarks(task) {
          // 记录当前滚动位置
          const container = self.containerEl.children[1];
          const scrollTop = container.scrollTop;
          const scrollLeft = container.scrollLeft;
          
          // 直接操作文件，保存标记
          const file = task.file;
          
          self.app.vault.read(file).then(content => {
            const lines = content.split('\n');
            let found = false;
            let hasImportantMark = false;
            let hasUrgentMark = false;
            let taskLineIndex = -1;
            
            // 找到任务行并检查是否已有标记
            for (let i = 0; i < lines.length; i++) {
              if (lines[i].trim().match(/^- \[[ xX]\] /)) {
                const title = lines[i].trim().replace(/^- \[[ xX]\] /, '').trim();
                if (title === task.title) {
                  taskLineIndex = i;
                  found = true;
                  
                  // 检查后续行是否有标记
                  let j = i + 1;
                  while (j < lines.length) {
                    const nextLine = lines[j].trim();
                    if (nextLine === '- 重要: true') {
                      hasImportantMark = true;
                      if (!task.important) {
                        // 如果任务不再重要，删除标记
                        lines.splice(j, 1);
                        j--; // 调整索引
                      }
                    } else if (nextLine === '- 紧急: true') {
                      hasUrgentMark = true;
                      if (!task.urgent) {
                        // 如果任务不再紧急，删除标记
                        lines.splice(j, 1);
                        j--; // 调整索引
                      }
                    } else if (!nextLine.startsWith('- 注释:')) {
                      // 遇到非注释、非标记行，停止检查
                      break;
                    }
                    j++;
                  }
                  
                  // 添加缺失的标记
                  if (task.important && !hasImportantMark) {
                    // 找到合适的位置插入标记（在注释之后）
                    let insertIndex = taskLineIndex + 1;
                    while (insertIndex < lines.length && lines[insertIndex].trim().startsWith('- 注释:')) {
                      insertIndex++;
                    }
                    lines.splice(insertIndex, 0, '- 重要: true');
                  }
                  if (task.urgent && !hasUrgentMark) {
                    // 找到合适的位置插入标记（在注释和重要标记之后）
                    let insertIndex = taskLineIndex + 1;
                    while (insertIndex < lines.length && 
                           (lines[insertIndex].trim().startsWith('- 注释:') || 
                            lines[insertIndex].trim() === '- 重要: true')) {
                      insertIndex++;
                    }
                    lines.splice(insertIndex, 0, '- 紧急: true');
                  }
                  
                  break;
                }
              }
            }
            
            if (found) {
              return self.app.vault.modify(file, lines.join('\n'));
            } else {
              return Promise.reject(new Error('任务未找到'));
            }
          }).then(() => {
            // 重新加载视图以显示标记
            return self.onOpen();
          }).then(() => {
            // 恢复滚动位置
            container.scrollTop = scrollTop;
            container.scrollLeft = scrollLeft;
          }).catch(err => {
            console.error('保存标记失败:', err);
          });
        }
      };
      
      // 添加事件监听器
      console.log('为dateContainer添加事件监听器:', dateContainer);
      dateContainer.addEventListener('contextmenu', dateContainer._contextMenuHandler);
      
      // 添加重要标记
      if (task.important) {
        const importantTag = markersContainer.createEl('span', { text: '重要' });
        importantTag.style.padding = '2px 6px';
        importantTag.style.borderRadius = '10px';
        importantTag.style.fontSize = '11px';
        importantTag.style.fontWeight = '500';
        importantTag.style.backgroundColor = '#ffd93d';
        importantTag.style.color = 'black';
      }
      
      // 添加紧急标记
      if (task.urgent) {
        const urgentTag = markersContainer.createEl('span', { text: '紧急' });
        urgentTag.style.padding = '2px 6px';
        urgentTag.style.borderRadius = '10px';
        urgentTag.style.fontSize = '11px';
        urgentTag.style.fontWeight = '500';
        urgentTag.style.backgroundColor = '#ff4757';
        urgentTag.style.color = 'white';
      }
      
      const taskEl = content.createEl('div', { cls: `timeline-task ${task.completed ? 'completed' : ''}` });
      const checkbox = taskEl.createEl('input', { type: 'checkbox' });
      checkbox.checked = task.completed;
      checkbox.addEventListener('change', async () => {
        if (checkbox.checked) {
          taskEl.addClass('completed');
          await this.updateTaskStatus(task.file, task.title, true);
        } else {
          taskEl.removeClass('completed');
          await this.updateTaskStatus(task.file, task.title, false);
        }
      });
      
      // 创建任务文本元素
      const taskText = task.title;
      
      // 创建一个容器来包含任务文本
      const taskContainer = taskEl.createEl('div', { cls: 'timeline-task-container' });
      // 为任务容器添加唯一标识
      taskContainer._uniqueId = 'task-' + Date.now() + '-' + Math.random().toString(36).substr(2, 9);
      taskContainer.style.display = 'flex';
      taskContainer.style.alignItems = 'center';
      taskContainer.style.width = '100%';
      taskContainer.style.padding = '10px';
      taskContainer.style.margin = '5px 0';
      taskContainer.style.backgroundColor = 'rgba(0, 0, 0, 0.05)';
      taskContainer.style.borderRadius = '4px';
      taskContainer.style.cursor = 'pointer';
      taskContainer.style.pointerEvents = 'auto';
      
      // 创建任务文本
      const taskSpan = taskContainer.createEl('span');
      // 添加调试信息
      console.log('任务标题:', taskText);
      console.log('任务注释:', task.comment);
      console.log('任务完整信息:', task);
      taskSpan.textContent = taskText;
      taskSpan.style.cursor = 'pointer';
      taskSpan.style.userSelect = 'text';
      taskSpan.style.flex = '1';
      taskSpan.style.whiteSpace = 'normal';
      taskSpan.style.wordBreak = 'break-word';
      
      // 显示注释信息
      if (task.comment) {
        // 为任务容器添加鼠标悬停事件 - 显示注释
        taskContainer.addEventListener('mouseenter', (e) => {
          // 创建工具提示元素
          const tooltip = document.createElement('div');
          tooltip.className = 'timeline-tooltip';
          tooltip.style.position = 'absolute';
          tooltip.style.background = 'rgba(0, 0, 0, 0.8)';
          tooltip.style.color = 'white';
          tooltip.style.padding = '8px';
          tooltip.style.borderRadius = '4px';
          tooltip.style.fontSize = '12px';
          tooltip.style.zIndex = '1000';
          tooltip.style.maxWidth = '300px';
          tooltip.style.maxHeight = '200px';
          tooltip.style.overflow = 'auto';
          tooltip.style.pointerEvents = 'none';
          
          // 设置工具提示内容，支持换行
          tooltip.innerHTML = task.comment.replace(/\n/g, '<br>');
          
          // 设置工具提示位置
          const rect = taskContainer.getBoundingClientRect();
          tooltip.style.top = `${rect.top + 30}px`;
          tooltip.style.left = `${rect.left}px`;
          
          // 添加到文档
          document.body.appendChild(tooltip);
          
          // 存储工具提示引用
          taskContainer._tooltip = tooltip;
        });
        
        // 为任务容器添加鼠标离开事件 - 隐藏注释
        taskContainer.addEventListener('mouseleave', () => {
          if (taskContainer._tooltip) {
            document.body.removeChild(taskContainer._tooltip);
            delete taskContainer._tooltip;
          }
        });
      }
      
      // 为整个任务容器添加双击事件 - 跳转到原始文件
      const self = this;
      taskContainer.addEventListener('dblclick', (e) => {
        e.stopPropagation();
        console.log('Double click detected on task:', task.title);
        try {
          console.log('Opening file:', task.file);
          console.log('App object:', self.app);
          console.log('Workspace object:', self.app.workspace);
          
          // 使用正确的Obsidian API方法打开文件
          if (self.app.workspace.getLeaf) {
            // 获取一个新的leaf并打开文件
            const leaf = self.app.workspace.getLeaf(true);
            if (leaf && leaf.openFile) {
              leaf.openFile(task.file);
              console.log('File opened successfully');
            } else {
              console.error('Leaf or openFile method not found');
            }
          } else {
            console.error('getLeaf method not found');
          }
        } catch (err) {
          console.error('Error opening file:', err);
        }
      });
      

      
      // 为任务容器添加右键菜单事件 - 添加注释
      console.log('为任务添加右键菜单事件:', task.title);
      
      // 测试任务容器是否存在
      console.log('任务容器元素:', taskContainer);
      console.log('任务容器样式:', window.getComputedStyle(taskContainer));
      
      taskContainer._contextMenuHandler = function(e) {
        // 关闭所有现有的上下文菜单
        const existingMenus = document.querySelectorAll('.timeline-context-menu');
        existingMenus.forEach(menu => {
          if (menu.parentNode === document.body) {
            document.body.removeChild(menu);
          }
        });
        
        e.preventDefault();
        e.stopPropagation();
        console.log('已阻止默认行为和事件冒泡');
        
        // 创建一个简单的输入对话框
        console.log('准备创建输入对话框');
        
        // 创建对话框容器
        const dialog = document.createElement('div');
        dialog.style.position = 'fixed';
        // 跟随鼠标点击位置显示
        dialog.style.top = `${e.clientY + 10}px`;
        dialog.style.left = `${e.clientX + 10}px`;
        dialog.style.backgroundColor = 'var(--background-primary)';
        dialog.style.border = '1px solid var(--background-modifier-border)';
        dialog.style.borderRadius = '8px';
        dialog.style.padding = '20px';
        dialog.style.zIndex = '1000';
        dialog.style.minWidth = '300px';
        // 确保对话框不会超出屏幕范围
        const dialogWidth = 340; // 对话框宽度（包括padding）
        const dialogHeight = 200; // 对话框高度（包括padding）
        const windowWidth = window.innerWidth;
        const windowHeight = window.innerHeight;
        
        if (e.clientX + dialogWidth > windowWidth) {
          dialog.style.left = `${windowWidth - dialogWidth - 10}px`;
        }
        
        if (e.clientY + dialogHeight > windowHeight) {
          dialog.style.top = `${windowHeight - dialogHeight - 10}px`;
        }
        
        // 创建标题
        const title = dialog.createEl('h3', { text: '添加注释' });
        title.style.marginTop = '0';
        title.style.marginBottom = '15px';
        
        // 创建输入框
        const input = dialog.createEl('textarea');
        input.style.width = '100%';
        input.style.height = '100px';
        input.style.padding = '8px';
        input.style.border = '1px solid var(--background-modifier-border)';
        input.style.borderRadius = '4px';
        input.style.backgroundColor = 'var(--background-secondary)';
        input.style.color = 'var(--text-normal)';
        input.placeholder = '请输入注释内容';
        
        // 创建按钮容器
        const buttonContainer = dialog.createEl('div');
        buttonContainer.style.display = 'flex';
        buttonContainer.style.justifyContent = 'flex-end';
        buttonContainer.style.gap = '10px';
        buttonContainer.style.marginTop = '15px';
        
        // 创建取消按钮
        const cancelButton = buttonContainer.createEl('button', { text: '取消' });
        cancelButton.style.padding = '8px 16px';
        cancelButton.style.border = '1px solid var(--background-modifier-border)';
        cancelButton.style.borderRadius = '4px';
        cancelButton.style.backgroundColor = 'var(--background-secondary)';
        cancelButton.style.color = 'var(--text-normal)';
        cancelButton.style.cursor = 'pointer';
        
        // 创建确认按钮
        const confirmButton = buttonContainer.createEl('button', { text: '确认' });
        confirmButton.style.padding = '8px 16px';
        confirmButton.style.border = '1px solid var(--interactive-accent)';
        confirmButton.style.borderRadius = '4px';
        confirmButton.style.backgroundColor = 'var(--interactive-accent)';
        confirmButton.style.color = 'white';
        confirmButton.style.cursor = 'pointer';
        
        // 添加到文档
        document.body.appendChild(dialog);
        
        // 聚焦输入框
        input.focus();
        
        // 取消按钮事件
        cancelButton.addEventListener('click', () => {
          document.body.removeChild(dialog);
        });
        
        // 确认按钮事件
        confirmButton.addEventListener('click', () => {
          const comment = input.value.trim();
          console.log('用户输入的注释:', comment);
          
          if (comment) {
            console.log('添加注释:', comment);
            
            // 获取当前时间
            const now = new Date();
            const month = now.getMonth() + 1;
            const day = now.getDate();
            const hours = now.getHours().toString().padStart(2, '0');
            const minutes = now.getMinutes().toString().padStart(2, '0');
            const timeStr = `${month}/${day} ${hours}:${minutes}`;
            
            // 组合注释内容，包含时间信息
            const commentWithTime = `${timeStr}：${comment}`;
            console.log('添加带时间的注释:', commentWithTime);
            
            // 直接操作文件
            const file = task.file;
            console.log('任务文件:', file);
            console.log('文件路径:', file.path);
            
            console.log('准备读取文件内容');
            // 记录当前滚动位置
            const container = self.containerEl.children[1];
            const scrollTop = container.scrollTop;
            const scrollLeft = container.scrollLeft;
            
            self.app.vault.read(file).then(content => {
              console.log('读取文件成功，内容长度:', content.length);
              const lines = content.split('\n');
              console.log('文件行数:', lines.length);
              let found = false;
              
              for (let i = 0; i < lines.length; i++) {
        if (lines[i].trim().match(/^- \[[ xX]\] /)) {
          const title = lines[i].trim().replace(/^- \[[ xX]\] /, '').trim();
                  console.log('检查任务行:', title, '是否匹配:', task.title);
                  if (title === task.title) {
                    // 在任务行后添加注释行
                    lines.splice(i + 1, 0, `  - 注释: ${commentWithTime}`);
                    found = true;
                    console.log('找到任务并添加注释，行号:', i);
                    break;
                  }
                }
              }
              
              if (found) {
                console.log('准备修改文件');
                return self.app.vault.modify(file, lines.join('\n'));
              } else {
                console.error('任务未找到:', task.title);
                return Promise.reject(new Error('任务未找到'));
              }
            }).then(() => {
              console.log('注释添加成功');
              // 先关闭对话框，再重新加载视图，减少闪屏
              document.body.removeChild(dialog);
              
              // 短暂延迟后重新加载视图，让对话框完全关闭
              return new Promise(resolve => {
                setTimeout(() => {
                  resolve(self.onOpen());
                }, 100);
              });
            }).then(() => {
              // 恢复滚动位置
              const container = self.containerEl.children[1];
              container.scrollTop = scrollTop;
              container.scrollLeft = scrollLeft;
              console.log('已恢复滚动位置');
            }).catch(err => {
              console.error('添加注释失败:', err);
              // 发生错误时也关闭对话框
              document.body.removeChild(dialog);
            });
          } else {
            // 没有输入内容，直接关闭对话框
            document.body.removeChild(dialog);
          }
        });
        
        // 点击对话框外部关闭
        dialog.addEventListener('click', (e) => {
          if (e.target === dialog) {
            document.body.removeChild(dialog);
          }
        });
        
        // 点击页面其他地方关闭对话框
        function closeDialogOnOutsideClick(e) {
          if (!dialog.contains(e.target)) {
            try {
              if (dialog && dialog.parentNode === document.body) {
                document.body.removeChild(dialog);
                document.removeEventListener('click', closeDialogOnOutsideClick);
              }
            } catch (err) {
              console.error('移除对话框时出错:', err);
            }
          }
        }
        
        // 添加外部点击事件监听器
        setTimeout(() => {
          document.addEventListener('click', closeDialogOnOutsideClick);
        }, 10);
      };
      
      // 添加事件监听器
      console.log('为taskContainer添加事件监听器:', taskContainer);
      taskContainer.addEventListener('contextmenu', taskContainer._contextMenuHandler);
      
      // 确保父元素不会阻止事件
      taskEl.style.pointerEvents = 'auto';
      content.style.pointerEvents = 'auto';
      timelineItem.style.pointerEvents = 'auto';
      
      
      
      timelineItem.createEl('div', { cls: 'timeline-dot' });
    });
  }

  // 显示添加注释菜单
  showAddCommentMenu(task, event) {
    console.log('Showing add comment menu');
    // 使用简单的prompt代替菜单，确保功能可用
    const comment = window.prompt('请输入注释内容:');
    if (comment) {
      console.log('Adding comment:', comment);
      this.addTaskComment(task, comment).then(() => {
        console.log('Comment added successfully');
        this.onOpen(); // 重新加载视图
      }).catch(err => {
        console.error('Error adding comment:', err);
      });
    }
  }

  // 获取任务的注释
  getTaskComment(task) {
    return task.comment || '';
  }

  // 添加任务注释
  async addTaskComment(task, comment) {
    try {
      const content = await this.app.vault.read(task.file);
      const lines = content.split('\n');
      
      for (let i = 0; i < lines.length; i++) {
        if (lines[i].trim().match(/^- \[[ xX]\] /)) {
          const title = lines[i].trim().replace(/^- \[[ xX]\] /, '').trim();
          if (title === task.title) {
            // 在任务行后添加注释行
            lines.splice(i + 1, 0, `  - 注释: ${comment}`);
            break;
          }
        }
      }
      
      await this.app.vault.modify(task.file, lines.join('\n'));
    } catch (error) {
      console.error('添加注释失败:', error);
    }
  }

  // 获取待办事项
  async getTasks() {
    const tasks = [];
    const { includeAllFolders, specificFolders } = this.plugin.settings;
    
    // 遍历所有文件
    for (const file of this.app.vault.getMarkdownFiles()) {
      // 检查是否在指定文件夹中
      if (!includeAllFolders) {
        const isInSpecificFolder = specificFolders.some(folder => 
          file.path.startsWith(folder)
        );
        if (!isInSpecificFolder) continue;
      }
      
      // 读取文件内容
      const content = await this.app.vault.read(file);
      
      // 提取待办事项
      const lines = content.split('\n');
      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        if (line.trim().match(/^- \[[ xX]\] /)) {
          const completed = line.trim().startsWith('- [x]') || line.trim().startsWith('- [X]');
          const title = line.trim().replace(/^- \[[ xX]\] /, '').trim();
          
          // 检查是否有注释和标记
          let comments = [];
          let important = false;
          let urgent = false;
          let j = i + 1;
          while (j < lines.length) {
            const nextLine = lines[j].trim();
            if (nextLine.startsWith('- 注释:')) {
              comments.push(nextLine.replace(/^- 注释: /, '').trim());
              j++;
            } else if (nextLine === '- 重要: true') {
              important = true;
              j++;
            } else if (nextLine === '- 紧急: true') {
              urgent = true;
              j++;
            } else {
              break;
            }
          }
          
          // 保持注释顺序，使最早的注释在上面（按时间顺序）
          
          tasks.push({
            id: `${file.path}:${i}`,
            title: title,
            completed: completed,
            file: file,
            created: file.stat.ctime,
            comment: comments.join('\n'),
            important: important,
            urgent: urgent
          });
        }
      }
    }
    
    return tasks;
  }

  // 更新任务状态
  async updateTaskStatus(file, taskTitle, completed) {
    try {
      const content = await this.app.vault.read(file);
      const lines = content.split('\n');
      
      for (let i = 0; i < lines.length; i++) {
        if (lines[i].trim().match(/^- \[[ xX]\] /)) {
          const title = lines[i].trim().replace(/^- \[[ xX]\] /, '').trim();
          if (title === taskTitle) {
            if (completed) {
            lines[i] = lines[i].replace(/^(- \[)[ xX](\].*)$/, '$1x$2');
          } else {
            lines[i] = lines[i].replace(/^(- \[)[ xX](\].*)$/, '$1 $2');
          }
            break;
          }
        }
      }
      
      await this.app.vault.modify(file, lines.join('\n'));
    } catch (error) {
      console.error('更新任务状态失败:', error);
    }
  }

  async onClose() {
    // 无需清理
  }
}

class TimelinePlugin extends Plugin {
  settings = null;
  notificationTimer = null;

  async onload() {
    console.log('加载时间轴插件');

    // 加载设置
    await this.loadSettings();

    // 注册时间轴视图
    this.registerView(
      TIMELINE_VIEW_TYPE,
      (leaf) => new TimelineView(leaf, this)
    );

    // 添加打开时间轴视图的命令
    this.addCommand({
      id: 'open-timeline-view',
      name: '打开时间轴视图',
      callback: () => {
        // 检查是否已经存在时间轴视图
        const existingLeaf = this.app.workspace.getLeavesOfType(TIMELINE_VIEW_TYPE)[0];
        if (existingLeaf) {
          // 激活现有的时间轴视图
          this.app.workspace.revealLeaf(existingLeaf);
        } else {
          // 创建新的时间轴视图
          this.app.workspace.getLeaf(true).setViewState({
            type: TIMELINE_VIEW_TYPE,
            active: true,
            state: {}
          });
        }
      },
    });

    // 添加手动检查时间提醒的命令
    this.addCommand({
      id: 'check-notifications',
      name: '检查时间提醒',
      callback: () => {
        this.checkNotificationTimes();
      },
    });

    // 添加到侧边栏
    this.addRibbonIcon('leaf', '时间轴', () => {
      // 检查是否已经存在时间轴视图
      const existingLeaf = this.app.workspace.getLeavesOfType(TIMELINE_VIEW_TYPE)[0];
      if (existingLeaf) {
        // 激活现有的时间轴视图
        this.app.workspace.revealLeaf(existingLeaf);
      } else {
        // 创建新的时间轴视图
        this.app.workspace.getLeaf(true).setViewState({
          type: TIMELINE_VIEW_TYPE,
          active: true,
          state: {}
        });
      }
    });

    // 添加设置选项
    this.addSettingTab(new TimelineSettingTab(this.app, this));

    // 添加文件监听，当文件变化时自动刷新时间轴
    this.registerEvent(
      this.app.vault.on('modify', async (file) => {
        // 只处理Markdown文件
        if (file.path.endsWith('.md')) {
          // 刷新所有时间轴视图
          const timelineLeaves = this.app.workspace.getLeavesOfType(TIMELINE_VIEW_TYPE);
          for (const leaf of timelineLeaves) {
            if (leaf.view instanceof TimelineView) {
              await leaf.view.onOpen();
            }
          }
        }
      })
    );

    // 添加文件创建监听
    this.registerEvent(
      this.app.vault.on('create', async (file) => {
        // 只处理Markdown文件
        if (file.path.endsWith('.md')) {
          // 刷新所有时间轴视图
          const timelineLeaves = this.app.workspace.getLeavesOfType(TIMELINE_VIEW_TYPE);
          for (const leaf of timelineLeaves) {
            if (leaf.view instanceof TimelineView) {
              await leaf.view.onOpen();
            }
          }
        }
      })
    );

    // 添加文件删除监听
    this.registerEvent(
      this.app.vault.on('delete', async (file) => {
        // 只处理Markdown文件
        if (file.path.endsWith('.md')) {
          // 刷新所有时间轴视图
          const timelineLeaves = this.app.workspace.getLeavesOfType(TIMELINE_VIEW_TYPE);
          for (const leaf of timelineLeaves) {
            if (leaf.view instanceof TimelineView) {
              await leaf.view.onOpen();
            }
          }
        }
      })
    );

    // 启动定时检查注释中的时间提醒
    this.startNotificationCheck();

    // 添加CSS样式
    const style = document.createElement('style');
    style.textContent = `
      /* 时间轴插件样式 */
      .timeline-wrapper {
        padding: 10px !important;
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif !important;
        position: relative !important;
      }

      .timeline-header {
        display: flex !important;
        justify-content: flex-end !important;
        align-items: center !important;
        margin-bottom: 15px !important;
        flex-wrap: wrap !important;
        gap: 8px !important;
        z-index: 100 !important;
        position: relative !important;
      }

      .timeline-filter {
        display: flex !important;
        gap: 8px !important;
        flex-wrap: wrap !important;
      }

      .timeline-filter button {
        padding: 6px 12px !important;
        border: 1px solid var(--background-modifier-border) !important;
        background-color: var(--background-secondary) !important;
        color: var(--text-normal) !important;
        border-radius: 4px !important;
        cursor: pointer !important;
        transition: all 0.2s ease !important;
        font-size: 14px !important;
        z-index: 100 !important;
        position: relative !important;
      }

      .timeline-filter button:hover {
        background-color: var(--background-primary) !important;
      }

      .timeline-filter button.active {
        background-color: var(--interactive-accent) !important;
        color: white !important;
        border-color: var(--interactive-accent) !important;
      }

      .timeline-task span {
        cursor: pointer !important;
      }

      .timeline-task span:hover {
        text-decoration: underline !important;
      }

      .timeline-task {
        position: relative !important;
      }

      .timeline {
        position: relative !important;
        max-width: 1200px !important;
        margin: 0 auto !important;
      }

      .timeline::after {
        content: '' !important;
        position: absolute !important;
        width: 4px !important;
        background-color: var(--background-primary-alt) !important;
        top: 0 !important;
        bottom: 0 !important;
        left: 50% !important;
        margin-left: -2px !important;
        border-radius: 2px !important;
      }

      .timeline-item {
        padding: 4px 30px !important;
        position: relative !important;
        width: 50% !important;
        box-sizing: border-box !important;
      }

      .timeline-item.left {
        left: 0 !important;
        margin-top: -40px !important;
      }

      .timeline-item.right {
        left: 50% !important;
        margin-top: -40px !important;
      }

      .timeline-dot {
        position: absolute !important;
        width: 16px !important;
        height: 16px !important;
        right: -8px !important;
        top: 16px !important;
        border-radius: 50% !important;
        background-color: var(--interactive-accent) !important;
        z-index: 1 !important;
      }

      .timeline-item.right .timeline-dot {
        left: -8px !important;
      }

      .timeline-content {
        padding: 10px !important;
        background-color: var(--background-secondary) !important;
        border-radius: 6px !important;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.08) !important;
        margin-bottom: 4px !important;
      }

      .timeline-date {
        font-size: 12px !important;
        color: var(--text-muted) !important;
        margin-bottom: 6px !important;
      }

      .timeline-task {
        display: flex !important;
        align-items: center !important;
        gap: 8px !important;
        line-height: 1.3 !important;
        font-size: 14px !important;
        position: relative !important;
      }
      
      

      .timeline-task.completed span {
        text-decoration: line-through !important;
        color: var(--text-muted) !important;
      }

      .timeline-task input[type="checkbox"] {
        accent-color: var(--interactive-accent) !important;
        margin: 0 !important;
        transform: scale(0.9) !important;
      }

      @media screen and (max-width: 768px) {
        .timeline::after {
          left: 25px !important;
        }

        .timeline-item {
          width: 100% !important;
          padding-left: 55px !important;
          padding-right: 20px !important;
        }

        .timeline-item.right {
          left: 0 !important;
        }

        .timeline-item .timeline-dot {
          left: 17px !important;
          right: auto !important;
        }
      }
    `;
    document.head.appendChild(style);
  }

  async onunload() {
    console.log('卸载时间轴插件');
    this.app.workspace.detachLeavesOfType(TIMELINE_VIEW_TYPE);
    // 清理定时器
    if (this.notificationTimer) {
      clearInterval(this.notificationTimer);
      this.notificationTimer = null;
    }
  }

  // 启动定时检查注释中的时间提醒
  startNotificationCheck() {
    // 每分钟检查一次
    this.notificationTimer = setInterval(() => {
      this.checkNotificationTimes();
    }, 60000);
    
    // 立即执行一次检查
    this.checkNotificationTimes();
  }

  // 检查注释中的时间提醒
  async checkNotificationTimes() {
    try {
      const now = new Date();
      const { includeAllFolders, specificFolders } = this.settings;
      
      // 遍历所有文件
      for (const file of this.app.vault.getMarkdownFiles()) {
        // 检查是否在指定文件夹中
        if (!includeAllFolders) {
          const isInSpecificFolder = specificFolders.some(folder => 
            file.path.startsWith(folder)
          );
          if (!isInSpecificFolder) continue;
        }
        
        // 读取文件内容
        const content = await this.app.vault.read(file);
        
        // 提取待办事项和注释
        const lines = content.split('\n');
        for (let i = 0; i < lines.length; i++) {
          const line = lines[i];
          if (line.trim().match(/^- \[[ xX]\] /)) {
            const title = line.trim().replace(/^- \[[ xX]\] /, '').trim();
            
            // 检查是否有注释
            let j = i + 1;
            while (j < lines.length) {
              const nextLine = lines[j];
              const trimmedNextLine = nextLine.trim();
              if (trimmedNextLine.startsWith('- 注释:')) {
                const comment = trimmedNextLine.replace(/^- 注释: /, '').trim();
                // 检查注释中是否包含时间格式 @YYYY-MM-DD HH:MM 或 @YYYY/MM/DD HH:MM
                const timeMatch = comment.match(/@(\d{4})[-/](\d{1,2})[-/](\d{1,2})\s*(\d{1,2}):(\d{2})/);
                if (timeMatch) {
                  const [, year, month, day, hour, minute] = timeMatch;
                  const notificationTime = new Date(year, month - 1, day, hour, minute);
                  
                  // 检查时间是否到达（前后5分钟内）
                  const timeDiff = Math.abs(notificationTime.getTime() - now.getTime());
                  if (timeDiff <= 5 * 60 * 1000) {
                    // 发送系统通知
                    new Notice(`时间提醒: ${title}\n${comment}`, 10000);
                  }
                }
                j++;
              } else if (trimmedNextLine.startsWith('- [') || trimmedNextLine === '') {
                // 如果遇到新的待办事项或空行，停止检查
                break;
              } else {
                // 其他类型的行，继续检查
                j++;
              }
            }
          }
        }
      }
    } catch (error) {
      console.error('检查时间提醒失败:', error);
    }
  }

  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }

  async saveSettings() {
    await this.saveData(this.settings);
  }
}

// 设置选项卡
class TimelineSettingTab extends PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }

  display() {
    const { containerEl } = this;
    containerEl.empty();

    containerEl.createEl('h2', { text: '时间轴插件设置' });

    // 包含所有文件夹选项
    new Setting(containerEl)
      .setName('包含所有文件夹')
      .setDesc('是否从所有文件夹中读取待办事项')
      .addToggle(toggle => toggle
        .setValue(this.plugin.settings.includeAllFolders)
        .onChange(async (value) => {
          this.plugin.settings.includeAllFolders = value;
          await this.plugin.saveSettings();
        }));

    // 指定文件夹选项
    new Setting(containerEl)
      .setName('指定文件夹')
      .setDesc('如果不包含所有文件夹，请输入要包含的文件夹路径（每行一个）')
      .addTextArea(text => text
        .setValue(this.plugin.settings.specificFolders.join('\n'))
        .onChange(async (value) => {
          this.plugin.settings.specificFolders = value.split('\n').filter(line => line.trim() !== '');
          await this.plugin.saveSettings();
        }))
      .addButton(button => button
        .setButtonText('清除')
        .onClick(async () => {
          this.plugin.settings.specificFolders = [];
          await this.plugin.saveSettings();
          this.display();
        }));

    // 任务筛选选项
    new Setting(containerEl)
      .setName('默认任务筛选')
      .setDesc('默认显示的任务类型')
      .addDropdown(dropdown => dropdown
        .addOption('all', '全部')
        .addOption('completed', '已完成')
        .addOption('pending', '未完成')
        .setValue(this.plugin.settings.taskFilter)
        .onChange(async (value) => {
          this.plugin.settings.taskFilter = value;
          await this.plugin.saveSettings();
        }));

    // 时间轴名称选项
    new Setting(containerEl)
      .setName('时间轴名称')
      .setDesc('时间轴视图的标题')
      .addText(text => text
        .setValue(this.plugin.settings.timelineName)
        .onChange(async (value) => {
          this.plugin.settings.timelineName = value;
          await this.plugin.saveSettings();
        }));
  }
}

module.exports = TimelinePlugin;